services:
  postgres:
    build: postgres/
    image: postgresdb:latest
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - dbdisk:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  pgadmin4:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=ricky@example.com
      - PGADMIN_DEFAULT_PASSWORD=mysecretpassword
    depends_on:
      - postgres
    ports:
      - "8080:80"
    volumes:
      - pgadmindisk:/var/lib/pgadmin
  goapi:
    build: 
      context: goapi/
      args:
        NODE_EXPORTER_VERSION: 1.6.1
    image: goapi:latest
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "19229:19229"
  integtest:
    build: integtest/
    image: integtest:latest
    depends_on:
      - goapi
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - promdata:/prometheus
  # grafana:
  #   image: grafana/grafana
  #   container_name: grafana
  #   ports:
  #     - 3000:3000
  #   restart: unless-stopped
  #   environment:
  #     - GF_SECURITY_ADMIN_USER=admin
  #     - GF_SECURITY_ADMIN_PASSWORD=grafana
  #   volumes:
  #     - ./grafana:/etc/grafana/provisioning/datasources
volumes:
  dbdisk: {}
  pgadmindisk: {}
  promdata: {}
    